DROP TABLE IF EXISTS exchange_rates;
CREATE TABLE exchange_rates (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    rate DECIMAL(9, 6) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);